In [1]:
import sqlite3
import numpy
import scipy
import pandas

In [51]:
db  = sqlite3.connect("../data/database.sqlite")
cur = db.cursor()

Match = pandas.read_sql_query("select * from Match", db, index_col= "id")
playerAttributes = pandas.read_sql_query("select * from Player_Attributes",db, index_col = "id")

for col_name in list(Match)[0:76]:
    cur.execute("DELETE from Match WHERE {} IS NULL".format(col_name))
db.commit()

Match = pandas.read_sql_query("select * from Match", db, index_col= "id")
playerAttributes = pandas.read_sql_query("select * from Player_Attributes",db, index_col = "id")

(21361, 76)

In [10]:
Match

['country_id',
 'league_id',
 'season',
 'stage',
 'date',
 'match_api_id',
 'home_team_api_id',
 'away_team_api_id',
 'home_team_goal',
 'away_team_goal',
 'home_player_X1',
 'home_player_X2',
 'home_player_X3',
 'home_player_X4',
 'home_player_X5',
 'home_player_X6',
 'home_player_X7',
 'home_player_X8',
 'home_player_X9',
 'home_player_X10',
 'home_player_X11',
 'away_player_X1',
 'away_player_X2',
 'away_player_X3',
 'away_player_X4',
 'away_player_X5',
 'away_player_X6',
 'away_player_X7',
 'away_player_X8',
 'away_player_X9',
 'away_player_X10',
 'away_player_X11',
 'home_player_Y1',
 'home_player_Y2',
 'home_player_Y3',
 'home_player_Y4',
 'home_player_Y5',
 'home_player_Y6',
 'home_player_Y7',
 'home_player_Y8',
 'home_player_Y9',
 'home_player_Y10',
 'home_player_Y11',
 'away_player_Y1',
 'away_player_Y2',
 'away_player_Y3',
 'away_player_Y4',
 'away_player_Y5',
 'away_player_Y6',
 'away_player_Y7',
 'away_player_Y8',
 'away_player_Y9',
 'away_player_Y10',
 'away_player_Y11',
 'home_player_1',
 'home_player_2',
 'home_player_3',
 'home_player_4',
 'home_player_5',
 'home_player_6',
 'home_player_7',
 'home_player_8',
 'home_player_9',
 'home_player_10',
 'home_player_11',
 'away_player_1',
 'away_player_2',
 'away_player_3',
 'away_player_4',
 'away_player_5',
 'away_player_6',
 'away_player_7',
 'away_player_8',
 'away_player_9',
 'away_player_10',
 'away_player_11']

In [45]:
Outcome = lambda x: numpy.piecewise(x,[x>0,x==0,x<0],[1,0,-1])
Match = Match.assign(Match_outcome = Match.home_team_goal-Match.away_team_goal)
Match.Match_outcome = Match.Match_outcome.apply(Outcome)

In [37]:
Outcome(numpy.array([-1,0,2,3,4]))

array([-1,  0,  1,  1,  1])

In [46]:
Match

,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,away_team_goal,...,away_player_3,away_player_4,away_player_5,away_player_6,away_player_7,away_player_8,away_player_9,away_player_10,away_player_11,Match_outcome
id,,,,,,,,,,,,,,,,,,,,,
146,1,1,2008/2009,24,2009-02-27 00:00:00,493017,8203,9987,2,1,...,148313.0,104411.0,148314.0,37202.0,43158.0,9307.0,42153.0,32690.0,38782.0,1
154,1,1,2008/2009,25,2009-03-08 00:00:00,493025,9984,8342,1,3,...,11736.0,37858.0,38366.0,37983.0,39578.0,38336.0,52280.0,27423.0,38440.0,0
156,1,1,2008/2009,25,2009-03-07 00:00:00,493027,8635,10000,2,0,...,37903.0,37889.0,94030.0,37893.0,37981.0,131531.0,130027.0,38231.0,131530.0,1
163,1,1,2008/2009,26,2009-03-13 00:00:00,493034,8203,8635,2,1,...,38389.0,31316.0,164694.0,30949.0,38378.0,38383.0,38393.0,38253.0,37069.0,1
169,1,1,2008/2009,26,2009-03-14 00:00:00,493040,10000,9999,0,0,...,16387.0,94288.0,94284.0,45832.0,26669.0,33671.0,163670.0,37945.0,33622.0,0
174,1,1,2008/2009,27,2009-03-22 00:00:00,493045,9991,10000,1,0,...,37886.0,37903.0,94030.0,37981.0,131531.0,131530.0,130027.0,38231.0,75500.0,1
177,1,1,2008/2009,27,2009-03-21 00:00:00,493048,9999,8203,1,0,...,67950.0,67958.0,164352.0,67898.0,37112.0,67959.0,148286.0,33657.0,26502.0,1
190,1,1,2008/2009,29,2009-04-12 00:00:00,493061,8635,8342,1,0,...,21812.0,11736.0,37858.0,37983.0,27364.0,38336.0,38366.0,27423.0,38440.0,1
191,1,1,2008/2009,29,2009-04-10 00:00:00,493062,9999,9987,1,0,...,38293.0,104411.0,148314.0,38782.0,43158.0,20445.0,32690.0,37202.0,38794.0,1
218,1,1,2008/2009,31,2009-04-26 00:00:00,493080,9984,9987,1,2,...,38293.0,104411.0,148314.0,9307.0,39498.0,43158.0,20445.0,32690.0,37202.0,0
220,1,1,2008/2009,31,2009-04-26 00:00:00,493082,9999,9991,1,3,...,38255.0,12473.0,104382.0,33662.0,38233.0,32760.0,38229.0,12574.0,46335.0,0
227,1,1,2008/2009,32,2009-05-02 00:00:00,493089,10000,9985,0,0,...,30692.0,38800.0,47411.0,35412.0,39631.0,39591.0,148335.0,37262.0,148315.0,0
230,1,1,2008/2009,32,2009-05-02 00:00:00,493092,9991,9984,2,1,...,37051.0,37038.0,38186.0,27110.0,37957.0,37909.0,104386.0,38251.0,12692.0,1
232,1,1,2008/2009,32,2009-05-02 00:00:00,493094,10001,9999,1,0,...,38247.0,16387.0,26669.0,33671.0,94284.0,163670.0,33622.0,148336.0,94288.0,1
235,1,1,2008/2009,33,2009-05-09 00:00:00,493097,9985,8342,2,0,...,38342.0,11736.0,38441.0,37979.0,27364.0,38336.0,38366.0,38440.0,34025.0,1
241,1,1,2008/2009,33,2009-05-09 00:00:00,493103,8635,9999,3,1,...,37945.0,38247.0,94284.0,45832.0,26669.0,33671.0,163670.0,148336.0,33622.0,1
243,1,1,2008/2009,33,2009-05-09 00:00:00,493105,9984,10001,2,1,...,38339.0,38343.0,38353.0,21834.0,39848.0,17883.0,50160.0,37953.0,30404.0,1
244,1,1,2008/2009,34,2009-05-16 00:00:00,493106,9987,8635,0,2,...,38388.0,13423.0,38389.0,30949.0,38393.0,38253.0,38798.0,38383.0,37069.0,0
245,1,1,2008/2009,34,2009-05-16 00:00:00,493107,9991,9985,0,1,...,38800.0,37861.0,156551.0,35412.0,26224.0,39631.0,39591.0,37262.0,38369.0,0
309,1,1,2009/2010,1,2009-08-02 00:00:00,665321,9984,9991,1,3,...,38255.0,12473.0,41109.0,33662.0,37044.0,26916.0,37065.0,12574.0,46335.0,0
310,1,1,2009/2010,1,2009-08-01 00:00:00,665322,9994,10000,1,1,...,37903.0,37889.0,94030.0,37902.0,37886.0,37981.0,131531.0,75500.0,130027.0,0
311,1,1,2009/2010,1,2009-08-01 00:00:00,665323,8571,8635,0,2,...,38388.0,13423.0,38389.0,38378.0,38383.0,38393.0,38253.0,37069.0,46552.0,0
314,1,1,2009/2010,10,2009-10-04 00:00:00,665411,8342,8635,4,2,...,38388.0,38389.0,38253.0,38378.0,38383.0,38393.0,106013.0,37069.0,12692.0,1
318,1,1,2009/2010,10,2009-10-03 00:00:00,665417,8203,9994,2,0,...,39594.0,25465.0,38273.0,38945.0,38290.0,95609.0,15662.0,34334.0,69629.0,1
320,1,1,2009/2010,10,2009-10-03 00:00:00,665421,9993,10001,3,1,...,43049.0,21834.0,67896.0,37025.0,38343.0,179058.0,182605.0,39848.0,25619.0,1
321,1,1,2009/2010,11,2009-10-18 00:00:00,665425,8342,9991,1,0,...,38337.0,12473.0,104382.0,33662.0,26916.0,32760.0,37065.0,12574.0,46335.0,1
323,1,1,2009/2010,11,2009-10-18 00:00:00,665427,9987,8203,1,2,...,6800.0,39389.0,164352.0,67898.0,37112.0,38969.0,178291.0,17276.0,148286.0,0
324,1,1,2009/2010,11,2009-10-17 00:00:00,665429,10000,9993,4,0,...,36849.0,36845.0,38322.0,38371.0,36852.0,38784.0,38786.0,33622.0,178284.0,1
325,1,1,2009/2010,11,2009-10-17 00:00:00,665430,9994,9984,1,1,...,37021.0,38789.0,37051.0,38357.0,37957.0,38782.0,104386.0,78462.0,38251.0,0
327,1,1,2009/2010,11,2009-10-17 00:00:00,665435,10001,9985,2,0,...,37861.0,47411.0,129462.0,32573.0,37262.0,35412.0,26224.0,148335.0,38369.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25943,24558,24558,2015/2016,35,2016-05-22 00:00:00,1992224,10192,9931,2,3,...,22834.0,705484.0,181211.0,438780.0,114738.0,402975.0,34035.0,384376.0,726956.0,0
25944,24558,24558,2015/2016,35,2016-05-22 00:00:00,1992234,10190,10199,1,4,...,150007.0,178119.0,114792.0,95257.0,260708.0,570830.0,36382.0,304860.0,34082.0,0
25945,24558,24558,2015/2016,36,2016-05-25 00:00:00,1992225,9931,9956,0,1,...,177689.0,696435.0,42258.0,173936.0,39979.0,614540.0,291106.0,80564.0,289472.0,0
25946,24558,24558,2015/2016,36,2016-05-25 00:00:00,1992226,7896,10190,3,0,...,638592.0,413155.0,210423.0,45780.0,176298.0,119839.0,566785.0,92094.0,35831.0,1
25947,24558,24558,2015/2016,36,2016-05-25 00:00:00,1992227,10199,10179,2,2,...,450493.0,32597.0,140495.0,106559.0,25840.0,634310.0,95230.0,427439.0,38601.0,0
25948,24558,24558,2015/2016,36,2016-05-25 00:00:00,1992228,10191,10192,0,3,...,108451.0,25815.0,733787.0,25860.0,245161.0,320184.0,45174.0,71764.0,37554.0,0
25949,24558,24558,2015/2016,36,2016-05-25 00:00:00,1992229,10243,9824,3,1,...,257845.0,41621.0,214344.0,114011.0,56868.0,488297.0,113227.0,531309.0,493418.0,1
25951,24558,24558,2015/2016,4,2015-08-08 00:00:00,1992067,10199,9931,1,3,...,172768.0,22834.0,40536.0,25772.0,207234.0,40274.0,114738.0,41726.0,527103.0,0
25952,24558,24558,2015/2016,4,2015-08-09 00:00:00,1992068,10190,10243,0,2,...,34268.0,656668.0,260964.0,67008.0,113235.0,92252.0,198082.0,540230.0,67306.0,0
25954,24558,24558,2015/2016,4,2015-08-09 00:00:00,1992070,10192,10191,3,1,...,67304.0,178210.0,158253.0,186524.0,25809.0,133126.0,520466.0,184610.0,232110.0,1
25955,24558,24558,2015/2016,5,2015-08-12 00:00:00,1992071,9931,10191,3,1,...,320183.0,8800.0,158253.0,133126.0,25809.0,121115.0,520466.0,232110.0,289732.0,1
25957,24558,24558,2015/2016,5,2015-08-12 00:00:00,1992073,10199,10190,0,1,...,638592.0,95220.0,120082.0,171229.0,308309.0,67333.0,66934.0,176298.0,35831.0,0
25958,24558,24558,2015/2016,5,2015-08-13 00:00:00,1992074,10179,10243,3,1,...,34268.0,656668.0,260964.0,92252.0,67008.0,113235.0,108525.0,254704.0,67306.0,1
25959,24558,24558,2015/2016,5,2015-08-13 00:00:00,1992075,9824,9956,3,3,...,155075.0,177689.0,513512.0,173936.0,39979.0,147959.0,451983.0,80564.0,289472.0,0
25961,24558,24558,2015/2016,6,2015-08-23 00:00:00,1992077,10179,10192,1,3,...,493185.0,25815.0,94553.0,320184.0,598355.0,190525.0,302079.0,45174.0,37554.0,0
25962,24558,24558,2015/2016,6,2015-08-23 00:00:00,1992078,10190,9956,0,2,...,294256.0,155075.0,513512.0,173936.0,39979.0,147959.0,451983.0,80564.0,289472.0,0
25963,24558,24558,2015/2016,6,2015-08-23 00:00:00,1992079,10191,9824,1,0,...,257845.0,41621.0,458806.0,358156.0,56868.0,214344.0,113227.0,114011.0,209371.0,1
25964,24558,24558,2015/2016,6,2015-08-22 00:00:00,1992080,10243,10199,2,5,...,150007.0,178119.0,42294.0,185518.0,260708.0,201704.0,95257.0,104646.0,34082.0,0
25966,24558,24558,2015/2016,7,2015-08-29 00:00:00,1992082,9824,10190,1,0,...,95220.0,638592.0,413155.0,143790.0,171229.0,66934.0,92094.0,195215.0,119839.0,1
25967,24558,24558,2015/2016,7,2015-08-30 00:00:00,1992083,10191,10179,0,2,...,202663.0,32597.0,114794.0,188114.0,25840.0,482200.0,538336.0,95230.0,275122.0,0
25968,24558,24558,2015/2016,7,2015-08-30 00:00:00,1992084,9931,10243,3,1,...,34268.0,197757.0,260964.0,92252.0,67008.0,198082.0,108525.0,194532.0,67306.0,1
25969,24558,24558,2015/2016,7,2015-08-30 00:00:00,1992085,9956,10192,3,2,...,108451.0,25815.0,94553.0,119702.0,320184.0,25860.0,302079.0,45174.0,422412.0,1
25970,24558,24558,2015/2016,8,2015-09-12 00:00:00,1992086,9931,10190,2,1,...,638592.0,67363.0,413155.0,45780.0,143790.0,66934.0,176298.0,92094.0,72628.0,1
25971,24558,24558,2015/2016,8,2015-09-12 00:00:00,1992087,10192,9824,4,0,...,25813.0,41621.0,358156.0,114011.0,42237.0,56868.0,209371.0,531309.0,113227.0,1
25972,24558,24558,2015/2016,8,2015-09-13 00:00:00,1992088,10199,9956,3,3,...,155075.0,294256.0,42258.0,173936.0,39979.0,147959.0,451983.0,80564.0,289472.0,0
25973,24558,24558,2015/2016,8,2015-09-13 00:00:00,1992089,10243,10191,3,3,...,320183.0,67304.0,67389.0,133126.0,186524.0,93223.0,121115.0,25809.0,289732.0,0
25975,24558,24558,2015/2016,9,2015-09-22 00:00:00,1992091,10190,10191,1,0,...,8800.0,67304.0,158253.0,133126.0,186524.0,93223.0,121115.0,232110.0,289732.0,1
25976,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992092,9824,10199,1,2,...,150007.0,178119.0,27232.0,570830.0,260708.0,201704.0,36382.0,34082.0,95257.0,0
25977,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992093,9956,10179,2,0,...,202663.0,32597.0,114794.0,188114.0,25840.0,482200.0,95230.0,451335.0,275122.0,1
25979,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992095,10192,9931,4,3,...,172768.0,22834.0,458806.0,207234.0,25772.0,40274.0,34035.0,41726.0,527103.0,1

In [49]:
Match

,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,away_team_goal,...,SJA,VCH,VCD,VCA,GBH,GBD,GBA,BSH,BSD,BSA
id,,,,,,,,,,,,,,,,,,,,,
1,1,1,2008/2009,1,2008-08-17 00:00:00,492473,9987,9993,1,1,...,4.00,1.65,3.40,4.50,1.78,3.25,4.00,1.73,3.40,4.20
2,1,1,2008/2009,1,2008-08-16 00:00:00,492474,10000,9994,0,0,...,3.80,2.00,3.25,3.25,1.85,3.25,3.75,1.91,3.25,3.60
3,1,1,2008/2009,1,2008-08-16 00:00:00,492475,9984,8635,0,3,...,2.50,2.35,3.25,2.65,2.50,3.20,2.50,2.30,3.20,2.75
4,1,1,2008/2009,1,2008-08-17 00:00:00,492476,9991,9998,5,0,...,7.50,1.45,3.75,6.50,1.50,3.75,5.50,1.44,3.75,6.50
5,1,1,2008/2009,1,2008-08-16 00:00:00,492477,7947,9985,1,3,...,1.73,4.50,3.40,1.65,4.50,3.50,1.65,4.75,3.30,1.67
6,1,1,2008/2009,1,2008-09-24 00:00:00,492478,8203,8342,1,1,...,1.67,4.35,3.40,1.70,4.50,3.40,1.70,NaN,NaN,NaN
7,1,1,2008/2009,1,2008-08-16 00:00:00,492479,9999,8571,2,2,...,3.60,2.10,3.25,3.00,1.85,3.25,3.75,2.10,3.25,3.10
8,1,1,2008/2009,1,2008-08-16 00:00:00,492480,4049,9996,1,2,...,2.40,2.80,3.25,2.25,2.80,3.20,2.25,2.88,3.25,2.20
9,1,1,2008/2009,1,2008-08-16 00:00:00,492481,10001,9986,1,0,...,3.10,2.25,3.25,2.80,2.20,3.30,2.80,2.25,3.20,2.80
10,1,1,2008/2009,10,2008-11-01 00:00:00,492564,8342,8571,4,1,...,10.00,1.30,4.35,8.50,1.25,5.00,10.00,1.29,4.50,9.00
11,1,1,2008/2009,10,2008-10-31 00:00:00,492565,9985,9986,1,2,...,10.00,1.28,4.50,8.50,1.25,5.00,10.00,1.25,5.00,9.00
12,1,1,2008/2009,10,2008-11-02 00:00:00,492566,10000,9991,0,2,...,2.50,2.65,3.30,2.30,2.60,3.25,2.50,2.62,3.20,2.38
13,1,1,2008/2009,10,2008-11-01 00:00:00,492567,9994,9998,0,0,...,4.25,2.00,3.20,3.40,1.85,3.30,4.00,1.83,3.30,3.80
14,1,1,2008/2009,10,2008-11-01 00:00:00,492568,7947,10001,2,2,...,2.38,2.75,3.20,2.30,2.75,3.25,2.35,2.75,3.20,2.30
15,1,1,2008/2009,10,2008-11-01 00:00:00,492569,8203,9999,1,2,...,4.75,1.70,3.40,4.35,1.75,3.40,4.25,1.70,3.40,4.33
16,1,1,2008/2009,10,2008-11-01 00:00:00,492570,9996,9984,0,1,...,2.88,2.20,3.25,2.90,2.30,3.25,2.85,2.30,3.20,2.75
17,1,1,2008/2009,10,2008-11-01 00:00:00,492571,4049,9987,1,3,...,1.62,5.50,3.50,1.55,5.25,3.60,1.60,6.00,3.60,1.50
18,1,1,2008/2009,10,2008-11-02 00:00:00,492572,9993,8635,1,3,...,1.80,3.60,3.25,1.90,4.10,3.40,1.80,3.80,3.30,1.83
19,1,1,2008/2009,11,2008-11-08 00:00:00,492573,8635,9994,2,3,...,9.00,1.28,4.50,8.50,1.30,4.75,7.50,1.30,4.50,8.50
20,1,1,2008/2009,11,2008-11-08 00:00:00,492574,9998,9996,0,0,...,2.75,2.35,3.25,2.65,2.30,3.20,2.75,2.30,3.25,2.70
21,1,1,2008/2009,11,2008-11-09 00:00:00,492575,9986,8342,2,2,...,2.10,3.25,3.25,2.00,3.10,3.20,2.15,3.10,3.25,2.10
22,1,1,2008/2009,11,2008-11-07 00:00:00,492576,9984,10000,2,0,...,4.25,1.75,3.25,4.35,1.80,3.30,4.20,1.70,3.30,4.50
23,1,1,2008/2009,11,2008-11-08 00:00:00,492577,9991,7947,1,1,...,7.00,1.35,4.00,7.50,1.40,4.20,7.00,1.36,4.20,7.00
24,1,1,2008/2009,11,2008-11-08 00:00:00,492578,9999,4049,1,2,...,4.00,1.80,3.25,4.00,1.85,3.30,4.00,1.80,3.30,4.00
25,1,1,2008/2009,11,2008-11-08 00:00:00,492579,8571,8203,0,0,...,3.50,2.00,3.25,3.25,1.95,3.20,3.50,2.00,3.25,3.30
26,1,1,2008/2009,11,2008-11-08 00:00:00,492580,10001,9987,1,0,...,2.60,2.40,3.25,2.60,2.50,3.25,2.50,2.50,3.20,2.50
27,1,1,2008/2009,11,2008-11-09 00:00:00,492581,9993,9985,1,3,...,1.95,3.75,3.25,1.85,3.60,3.25,1.95,3.50,3.30,1.91
28,1,1,2008/2009,12,2008-11-16 00:00:00,492582,8342,8635,1,1,...,3.30,2.25,3.10,2.80,2.10,3.20,3.20,2.20,3.20,2.90
29,1,1,2008/2009,12,2008-11-15 00:00:00,492583,9987,9999,1,1,...,10.00,1.25,5.00,9.00,1.27,5.00,8.50,1.25,5.00,9.00
30,1,1,2008/2009,12,2008-11-15 00:00:00,492584,10000,9993,2,2,...,3.40,2.10,3.30,3.10,2.00,3.20,3.50,2.00,3.25,3.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25950,24558,24558,2015/2016,4,2015-08-08 00:00:00,1992066,9956,7896,6,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25951,24558,24558,2015/2016,4,2015-08-08 00:00:00,1992067,10199,9931,1,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25952,24558,24558,2015/2016,4,2015-08-09 00:00:00,1992068,10190,10243,0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25953,24558,24558,2015/2016,4,2015-08-09 00:00:00,1992069,9824,10179,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25954,24558,24558,2015/2016,4,2015-08-09 00:00:00,1992070,10192,10191,3,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25955,24558,24558,2015/2016,5,2015-08-12 00:00:00,1992071,9931,10191,3,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25956,24558,24558,2015/2016,5,2015-08-12 00:00:00,1992072,10192,7896,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25957,24558,24558,2015/2016,5,2015-08-12 00:00:00,1992073,10199,10190,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25958,24558,24558,2015/2016,5,2015-08-13 00:00:00,1992074,10179,10243,3,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25959,24558,24558,2015/2016,5,2015-08-13 00:00:00,1992075,9824,9956,3,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25960,24558,24558,2015/2016,6,2015-08-22 00:00:00,1992076,7896,9931,1,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25961,24558,24558,2015/2016,6,2015-08-23 00:00:00,1992077,10179,10192,1,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25962,24558,24558,2015/2016,6,2015-08-23 00:00:00,1992078,10190,9956,0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25963,24558,24558,2015/2016,6,2015-08-23 00:00:00,1992079,10191,9824,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25964,24558,24558,2015/2016,6,2015-08-22 00:00:00,1992080,10243,10199,2,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25965,24558,24558,2015/2016,7,2015-08-29 00:00:00,1992081,7896,10199,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25966,24558,24558,2015/2016,7,2015-08-29 00:00:00,1992082,9824,10190,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25967,24558,24558,2015/2016,7,2015-08-30 00:00:00,1992083,10191,10179,0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25968,24558,24558,2015/2016,7,2015-08-30 00:00:00,1992084,9931,10243,3,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25969,24558,24558,2015/2016,7,2015-08-30 00:00:00,1992085,9956,10192,3,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25970,24558,24558,2015/2016,8,2015-09-12 00:00:00,1992086,9931,10190,2,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25971,24558,24558,2015/2016,8,2015-09-12 00:00:00,1992087,10192,9824,4,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25972,24558,24558,2015/2016,8,2015-09-13 00:00:00,1992088,10199,9956,3,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25973,24558,24558,2015/2016,8,2015-09-13 00:00:00,1992089,10243,10191,3,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25974,24558,24558,2015/2016,8,2015-09-13 00:00:00,1992090,10179,7896,3,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25975,24558,24558,2015/2016,9,2015-09-22 00:00:00,1992091,10190,10191,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25976,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992092,9824,10199,1,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25977,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992093,9956,10179,2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25978,24558,24558,2015/2016,9,2015-09-22 00:00:00,1992094,7896,10243,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25979,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992095,10192,9931,4,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN